# Deploy for pentagame.cobalt.rocks with rsync+ssh of a custom image
name: CD

# Controls when the action will run.
on:
    # Triggers the workflow on push events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        image: registry.gitlab.cobalt.rocks/cobalt/docker-builder/zola-builder:latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Cache theme & output
              uses: actions/cache@v2
              with:
                  path: |
                      public/
                      node_modules/
                      static/fonts/
                  key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

            # Install static assets
            - name: Install & Build Assets
              run: npm i --save-dev

            # Build page
            - name: Build page
              run: npm run build

            - name: ssh + rsync deploy
              uses: easingthemes/ssh-deploy@v2.1.6
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-PL -rvzuc --delete'
                  SOURCE: 'public/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
