# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Cache theme & output
        uses: actions/cache@v2
        with:
          path: |
            theme/
            output/
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      # Install static assets
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: theme/static/
      - name: Build assets
        run: |
          cd theme/static/
          npm run production-compile
          cd ../../

      # Install python dependencies 
      - name: Install python dependencies and create html files
        run: |
          python3 -m pip install -r requirements.txt
          make publish
          
      - name: ssh + rsync deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-PzuL"
          SOURCE: "output/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
